<?php

/**
 * BaseTrebuchetCategoryAsset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $trebuchet_category_id
 * @property integer $trebuchet_asset_id
 * @property boolean $is_active
 * @property integer $display_order
 * @property TrebuchetCategory $TrebuchetCategory
 * @property TrebuchetAsset $TrebuchetAsset
 * 
 * @method integer                getTrebuchetCategoryId()   Returns the current record's "trebuchet_category_id" value
 * @method integer                getTrebuchetAssetId()      Returns the current record's "trebuchet_asset_id" value
 * @method boolean                getIsActive()              Returns the current record's "is_active" value
 * @method integer                getDisplayOrder()          Returns the current record's "display_order" value
 * @method TrebuchetCategory      getTrebuchetCategory()     Returns the current record's "TrebuchetCategory" value
 * @method TrebuchetAsset         getTrebuchetAsset()        Returns the current record's "TrebuchetAsset" value
 * @method TrebuchetCategoryAsset setTrebuchetCategoryId()   Sets the current record's "trebuchet_category_id" value
 * @method TrebuchetCategoryAsset setTrebuchetAssetId()      Sets the current record's "trebuchet_asset_id" value
 * @method TrebuchetCategoryAsset setIsActive()              Sets the current record's "is_active" value
 * @method TrebuchetCategoryAsset setDisplayOrder()          Sets the current record's "display_order" value
 * @method TrebuchetCategoryAsset setTrebuchetCategory()     Sets the current record's "TrebuchetCategory" value
 * @method TrebuchetCategoryAsset setTrebuchetAsset()        Sets the current record's "TrebuchetAsset" value
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrebuchetCategoryAsset extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trebuchet_category_asset');
        $this->hasColumn('trebuchet_category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('trebuchet_asset_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TrebuchetCategory', array(
             'local' => 'trebuchet_category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('TrebuchetAsset', array(
             'local' => 'trebuchet_asset_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}