<?php

/**
 * BaseTrebuchetCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $trebuchet_category_id
 * @property string $title
 * @property string $description
 * @property string $image
 * @property integer $display_order
 * @property boolean $is_active
 * @property TrebuchetCategory $Parent
 * @property Doctrine_Collection $Assets
 * @property Doctrine_Collection $Children
 * @property Doctrine_Collection $TrebuchetAsset
 * 
 * @method integer             getTrebuchetCategoryId()   Returns the current record's "trebuchet_category_id" value
 * @method string              getTitle()                 Returns the current record's "title" value
 * @method string              getDescription()           Returns the current record's "description" value
 * @method string              getImage()                 Returns the current record's "image" value
 * @method integer             getDisplayOrder()          Returns the current record's "display_order" value
 * @method boolean             getIsActive()              Returns the current record's "is_active" value
 * @method TrebuchetCategory   getParent()                Returns the current record's "Parent" value
 * @method Doctrine_Collection getAssets()                Returns the current record's "Assets" collection
 * @method Doctrine_Collection getChildren()              Returns the current record's "Children" collection
 * @method Doctrine_Collection getTrebuchetAsset()        Returns the current record's "TrebuchetAsset" collection
 * @method TrebuchetCategory   setTrebuchetCategoryId()   Sets the current record's "trebuchet_category_id" value
 * @method TrebuchetCategory   setTitle()                 Sets the current record's "title" value
 * @method TrebuchetCategory   setDescription()           Sets the current record's "description" value
 * @method TrebuchetCategory   setImage()                 Sets the current record's "image" value
 * @method TrebuchetCategory   setDisplayOrder()          Sets the current record's "display_order" value
 * @method TrebuchetCategory   setIsActive()              Sets the current record's "is_active" value
 * @method TrebuchetCategory   setParent()                Sets the current record's "Parent" value
 * @method TrebuchetCategory   setAssets()                Sets the current record's "Assets" collection
 * @method TrebuchetCategory   setChildren()              Sets the current record's "Children" collection
 * @method TrebuchetCategory   setTrebuchetAsset()        Sets the current record's "TrebuchetAsset" collection
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrebuchetCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trebuchet_category');
        $this->hasColumn('trebuchet_category_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TrebuchetCategory as Parent', array(
             'local' => 'trebuchet_category_id',
             'foreign' => 'id'));

        $this->hasMany('TrebuchetCategoryAsset as Assets', array(
             'local' => 'id',
             'foreign' => 'trebuchet_category_id'));

        $this->hasMany('TrebuchetCategory as Children', array(
             'local' => 'id',
             'foreign' => 'trebuchet_category_id'));

        $this->hasMany('TrebuchetAsset', array(
             'refClass' => 'TrebuchetCategoryAsset',
             'local' => 'trebuchet_category_id',
             'foreign' => 'trebuchet_asset_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}