<?php

/**
 * BaseTrebuchetAsset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $youtube_id
 * @property string $title
 * @property string $description
 * @property string $image
 * @property string $file1
 * @property string $file2
 * @property string $rating
 * @property string $duration
 * @property integer $display_order
 * @property boolean $is_active
 * @property Doctrine_Collection $TrebuchetCategories
 * @property Doctrine_Collection $Categories
 * 
 * @method string              getYoutubeId()           Returns the current record's "youtube_id" value
 * @method string              getTitle()               Returns the current record's "title" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method string              getImage()               Returns the current record's "image" value
 * @method string              getFile1()               Returns the current record's "file1" value
 * @method string              getFile2()               Returns the current record's "file2" value
 * @method string              getRating()              Returns the current record's "rating" value
 * @method string              getDuration()            Returns the current record's "duration" value
 * @method integer             getDisplayOrder()        Returns the current record's "display_order" value
 * @method boolean             getIsActive()            Returns the current record's "is_active" value
 * @method Doctrine_Collection getTrebuchetCategories() Returns the current record's "TrebuchetCategories" collection
 * @method Doctrine_Collection getCategories()          Returns the current record's "Categories" collection
 * @method TrebuchetAsset      setYoutubeId()           Sets the current record's "youtube_id" value
 * @method TrebuchetAsset      setTitle()               Sets the current record's "title" value
 * @method TrebuchetAsset      setDescription()         Sets the current record's "description" value
 * @method TrebuchetAsset      setImage()               Sets the current record's "image" value
 * @method TrebuchetAsset      setFile1()               Sets the current record's "file1" value
 * @method TrebuchetAsset      setFile2()               Sets the current record's "file2" value
 * @method TrebuchetAsset      setRating()              Sets the current record's "rating" value
 * @method TrebuchetAsset      setDuration()            Sets the current record's "duration" value
 * @method TrebuchetAsset      setDisplayOrder()        Sets the current record's "display_order" value
 * @method TrebuchetAsset      setIsActive()            Sets the current record's "is_active" value
 * @method TrebuchetAsset      setTrebuchetCategories() Sets the current record's "TrebuchetCategories" collection
 * @method TrebuchetAsset      setCategories()          Sets the current record's "Categories" collection
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrebuchetAsset extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trebuchet_asset');
        $this->hasColumn('youtube_id', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('title', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('file1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('file2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('rating', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('duration', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TrebuchetCategory as TrebuchetCategories', array(
             'refClass' => 'TrebuchetCategoryAsset',
             'local' => 'trebuchet_asset_id',
             'foreign' => 'trebuchet_category_id'));

        $this->hasMany('TrebuchetCategoryAsset as Categories', array(
             'local' => 'id',
             'foreign' => 'trebuchet_asset_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}