<?php

/**
 * BaseSonyAsset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $youtube_id
 * @property string $title
 * @property string $description
 * @property string $image
 * @property string $file1
 * @property string $file2
 * @property string $rating
 * @property string $duration
 * @property integer $display_order
 * @property boolean $is_active
 * @property Doctrine_Collection $SonyCategories
 * @property Doctrine_Collection $SonyCategoryAsset
 * 
 * @method string              getYoutubeId()         Returns the current record's "youtube_id" value
 * @method string              getTitle()             Returns the current record's "title" value
 * @method string              getDescription()       Returns the current record's "description" value
 * @method string              getImage()             Returns the current record's "image" value
 * @method string              getFile1()             Returns the current record's "file1" value
 * @method string              getFile2()             Returns the current record's "file2" value
 * @method string              getRating()            Returns the current record's "rating" value
 * @method string              getDuration()          Returns the current record's "duration" value
 * @method integer             getDisplayOrder()      Returns the current record's "display_order" value
 * @method boolean             getIsActive()          Returns the current record's "is_active" value
 * @method Doctrine_Collection getSonyCategories()    Returns the current record's "SonyCategories" collection
 * @method Doctrine_Collection getSonyCategoryAsset() Returns the current record's "SonyCategoryAsset" collection
 * @method SonyAsset           setYoutubeId()         Sets the current record's "youtube_id" value
 * @method SonyAsset           setTitle()             Sets the current record's "title" value
 * @method SonyAsset           setDescription()       Sets the current record's "description" value
 * @method SonyAsset           setImage()             Sets the current record's "image" value
 * @method SonyAsset           setFile1()             Sets the current record's "file1" value
 * @method SonyAsset           setFile2()             Sets the current record's "file2" value
 * @method SonyAsset           setRating()            Sets the current record's "rating" value
 * @method SonyAsset           setDuration()          Sets the current record's "duration" value
 * @method SonyAsset           setDisplayOrder()      Sets the current record's "display_order" value
 * @method SonyAsset           setIsActive()          Sets the current record's "is_active" value
 * @method SonyAsset           setSonyCategories()    Sets the current record's "SonyCategories" collection
 * @method SonyAsset           setSonyCategoryAsset() Sets the current record's "SonyCategoryAsset" collection
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSonyAsset extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sony_asset');
        $this->hasColumn('youtube_id', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('title', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('file1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('file2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('rating', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('duration', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SonyCategory as SonyCategories', array(
             'refClass' => 'SonyCategoryAsset',
             'local' => 'sony_asset_id',
             'foreign' => 'sony_category_id'));

        $this->hasMany('SonyCategoryAsset', array(
             'local' => 'id',
             'foreign' => 'sony_asset_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}