<?php

/**
 * BaseSonyCategoryAsset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sony_category_id
 * @property integer $sony_asset_id
 * @property boolean $is_active
 * @property integer $display_order
 * @property SonyAsset $SonyAsset
 * @property SonyCategory $SonyCategory
 * 
 * @method integer           getSonyCategoryId()   Returns the current record's "sony_category_id" value
 * @method integer           getSonyAssetId()      Returns the current record's "sony_asset_id" value
 * @method boolean           getIsActive()         Returns the current record's "is_active" value
 * @method integer           getDisplayOrder()     Returns the current record's "display_order" value
 * @method SonyAsset         getSonyAsset()        Returns the current record's "SonyAsset" value
 * @method SonyCategory      getSonyCategory()     Returns the current record's "SonyCategory" value
 * @method SonyCategoryAsset setSonyCategoryId()   Sets the current record's "sony_category_id" value
 * @method SonyCategoryAsset setSonyAssetId()      Sets the current record's "sony_asset_id" value
 * @method SonyCategoryAsset setIsActive()         Sets the current record's "is_active" value
 * @method SonyCategoryAsset setDisplayOrder()     Sets the current record's "display_order" value
 * @method SonyCategoryAsset setSonyAsset()        Sets the current record's "SonyAsset" value
 * @method SonyCategoryAsset setSonyCategory()     Sets the current record's "SonyCategory" value
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSonyCategoryAsset extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sony_category_asset');
        $this->hasColumn('sony_category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('sony_asset_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SonyAsset', array(
             'local' => 'sony_asset_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('SonyCategory', array(
             'local' => 'sony_category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}