<?php

/**
 * BaseSonyCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sony_category_id
 * @property string $title
 * @property string $description
 * @property string $image
 * @property integer $display_order
 * @property boolean $is_active
 * @property SonyCategory $Parent
 * @property Doctrine_Collection $Assets
 * @property Doctrine_Collection $SonyCategoryAsset
 * @property Doctrine_Collection $Children
 * 
 * @method integer             getSonyCategoryId()    Returns the current record's "sony_category_id" value
 * @method string              getTitle()             Returns the current record's "title" value
 * @method string              getDescription()       Returns the current record's "description" value
 * @method string              getImage()             Returns the current record's "image" value
 * @method integer             getDisplayOrder()      Returns the current record's "display_order" value
 * @method boolean             getIsActive()          Returns the current record's "is_active" value
 * @method SonyCategory        getParent()            Returns the current record's "Parent" value
 * @method Doctrine_Collection getAssets()            Returns the current record's "Assets" collection
 * @method Doctrine_Collection getSonyCategoryAsset() Returns the current record's "SonyCategoryAsset" collection
 * @method Doctrine_Collection getChildren()          Returns the current record's "Children" collection
 * @method SonyCategory        setSonyCategoryId()    Sets the current record's "sony_category_id" value
 * @method SonyCategory        setTitle()             Sets the current record's "title" value
 * @method SonyCategory        setDescription()       Sets the current record's "description" value
 * @method SonyCategory        setImage()             Sets the current record's "image" value
 * @method SonyCategory        setDisplayOrder()      Sets the current record's "display_order" value
 * @method SonyCategory        setIsActive()          Sets the current record's "is_active" value
 * @method SonyCategory        setParent()            Sets the current record's "Parent" value
 * @method SonyCategory        setAssets()            Sets the current record's "Assets" collection
 * @method SonyCategory        setSonyCategoryAsset() Sets the current record's "SonyCategoryAsset" collection
 * @method SonyCategory        setChildren()          Sets the current record's "Children" collection
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSonyCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sony_category');
        $this->hasColumn('sony_category_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SonyCategory as Parent', array(
             'local' => 'sony_category_id',
             'foreign' => 'id'));

        $this->hasMany('SonyAsset as Assets', array(
             'refClass' => 'SonyCategoryAsset',
             'local' => 'sony_category_id',
             'foreign' => 'sony_asset_id'));

        $this->hasMany('SonyCategoryAsset', array(
             'local' => 'id',
             'foreign' => 'sony_category_id'));

        $this->hasMany('SonyCategory as Children', array(
             'local' => 'id',
             'foreign' => 'sony_category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}