# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Astolfo
    description:  Content Manager System
    keywords:     symfony, doctrine, cms
    language:     pt-br
    robots:       index, follow

  #stylesheets:    [core.css]
  stylesheets:    [/initializr/css/bootstrap.min.css, /initializr/css/bootstrap-responsive.min.css, /initializr/css/style.css]

  ##javascripts:    [jquery-ui-1.8.7/jquery-1.4.4.min.js, jquery-ui-1.8.7/jquery-ui-1.8.7.custom.min.js]
  #javascripts:    [jquery-ui-1.8.7/jquery-1.4.4.min.js, jquery-1.7.2.min.js]
  javascripts:    [/initializr/js/libs/modernizr-2.5.3-respond-1.1.0.min.js, /initializr/js/libs/jquery-1.7.2.min.js, /initializr/js/libs/jquery.validate.min.js, /initializr/js/libs/messages_ptbr.js, /initializr/js/libs/bootstrap/bootstrap.min.js, /initializr/js/script.js]

  has_layout:     true
  layout:         layout
