generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SonyAsset
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sony_assets
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:            ""
        display:          [=youtube_id, image, =title, description, created_at]
        actions:          {}
        object_actions:   {}
        batch_actions:
          save:           ~
      filter:
        display:          [youtube_id, image, title, description, duration]
      form:
        display: 
          Description:    [slug, title, description, youtube_id, image, file1, file2]
          Availability:   [is_active]
          Categorization: [sony_categories_list, rating, duration]
      edit:    ~
      new:     ~
