generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Asset
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          asset_related_assets
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:            ""
        display:          [title, AssetType, Site, thumbnail]
        object_actions:
          _edit:        ~
          _delete:      ~
        batch_actions:
          save:           ~
        max_per_page:     10
      filter:
        display:          [title, asset_type_id, site_id]
      form:    ~
      edit:    ~
      new:     ~
