<?php

/**
 * AssetContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AssetContent extends BaseAssetContent
{

	public function postUpdate($values)
	{
		//clear cache
		@exec("rm /var/frontend/web/cache/".str_replace("http://", "", $this->Asset->retriveUrl2()));
	}
	
  public function render(){

    $replaceVideo4201 = '<object style="width: 420px; height: 236px;"><param name="movie" value="http://www.youtube.com/v/\\4?version=3\\5"><param name="allowFullScreen" value="true"><param name="allowScriptAccess" value="always"><embed src="http://www.youtube.com/v/\\4?version=3" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="420" height="236"></object>';
    $replaceVideo6401 = '<object style="width: 640px; height: 360px;"><param name="movie" value="http://www.youtube.com/v/\\4?version=3\\5"><param name="allowFullScreen" value="true"><param name="allowScriptAccess" value="always"><embed src="http://www.youtube.com/v/\\4?version=3" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="640" height="360"></object>';
    
    $replaceVideo420 = '<object style="width: 420px; height: 236px;"><param name="movie" value="http://www.youtube.com/v/\\5?version=3\\6"><param name="allowFullScreen" value="true"><param name="allowScriptAccess" value="always"><embed src="http://www.youtube.com/v/\\5?version=3" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="420" height="236"></object>';
    $replaceVideo640 = '<object style="width: 640px; height: 360px;"><param name="movie" value="http://www.youtube.com/v/\\5?version=3\\6"><param name="allowFullScreen" value="true"><param name="allowScriptAccess" value="always"><embed src="http://www.youtube.com/v/\\5?version=3" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="640" height="360"></object>';
    
    $replaceAudio = '<script type="text/javascript" src="/js/jquery-ui-1.8.7/jquery-1.4.4.min.js"></script><link href="/js/audioplayer/jPlayer.Blue.Monday.2.0.0/jplayer.blue.monday.css" rel="stylesheet" type="text/css" />
  <script type="text/javascript" src="/js/audioplayer/jquery.jplayer.js"></script>
  <script type="text/javascript">
  $(document).ready(function(){
    $("#jquery_jplayer_1").jPlayer({
      ready: function () {
        $(this).jPlayer("setMedia", {
          mp3: "http://cmais.com.br/uploads/assets/audio/default/\\2.mp3"
        }).jPlayer("play");
      },
      ended: function (event) {
        $(this).jPlayer("play");
      },
      swfPath: "./js",
      supplied: "mp3"
    });
  });
  </script>
  <div id="jquery_jplayer_1" class="jp-jplayer"></div>
    <div class="jp-audio">
      <div class="jp-type-single">
        <div id="jp_interface_1" class="jp-interface">
          <ul class="jp-controls">
            <li><a href="#" class="jp-play" tabindex="1">play</a></li>
            <li><a href="#" class="jp-pause" tabindex="1">pause</a></li>
            <li><a href="#" class="jp-stop" tabindex="1">stop</a></li>
            <li><a href="#" class="jp-mute" tabindex="1">mute</a></li>
            <li><a href="#" class="jp-unmute" tabindex="1">unmute</a></li>
          </ul>
          <div class="jp-progress">
            <div class="jp-seek-bar">
              <div class="jp-play-bar"></div>
            </div>
          </div>
          <div class="jp-volume-bar">
            <div class="jp-volume-bar-value"></div>
          </div>
          <div class="jp-current-time"></div>
          <div class="jp-duration"></div>
        </div>
        <div id="jp_playlist_1" class="jp-playlist">
          <ul>
            <li>Bubble</li>
          </ul>
        </div>
      </div>
  </div>';
    
    $content = $this->getContent();
    $content = preg_replace('/<img align="([^"]*)" alt="([^"]*)" src="\/images\/video-420.png" style="([^"]*)" youtubeid="([^"]*)" startfrom="([^"]*)" \/>/', $replaceVideo4201, $content);
    $content = preg_replace('/<img align="([^"]*)" alt="([^"]*)" src="\/images\/video-640.png" style="([^"]*)" youtubeid="([^"]*)" startfrom="([^"]*)" \/>/', $replaceVideo6401, $content);
    $content = preg_replace('/<img align="([^"]*)" alt="([^"]*)" border="([^"]*)" src="\/images\/video-420.png" style="([^"]*)" youtubeid="([^"]*)" startfrom="([^"]*)" \/>/', $replaceVideo420, $content);
    $content = preg_replace('/<img align="([^"]*)" alt="([^"]*)" border="([^"]*)" src="\/images\/video-640.png" style="([^"]*)" youtubeid="([^"]*)" startfrom="([^"]*)" \/>/', $replaceVideo640, $content);
    $content = preg_replace('/<img align="([^"]*)" alt="([^"]*)" border="([^"]*)" src="\/images\/audio.png" style="([^"]*)" \/>/', $replaceAudio, $content);

    print "<hr />".$content;
    die();

  }

	public function findOneByAssetId($assetId)
	{
	  $q = Doctrine_Core::getTable('AssetContent')
	    ->createQuery('c')
	    ->where('c.asset_id = ?', $assetId)
	    ->orderBy('c.created_at ASC');
	  return $q->execute();
	}
}
