<?php

/**
 * AssetQuestion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AssetQuestion extends BaseAssetQuestion
{
	
	public function postUpdate($values){
	}

  public function postDelete($values){
  }
  
  public function postInsert($values){
  }

}
