<?php

/**
 * Display
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Display extends BaseDisplay
{

  public function postDelete($values)
  {
    $log = new Log();
    $log->setAction('Delete');
    if(sfContext::hasInstance())
      $log->setUserId(sfContext::getInstance()->getUser()->getGuardUser()->getId());
    $log->setSiteId($this->Block->Section->Site->getId());
    $log->setAsset($this->getId());
    $log->setAssetTitle($this->getTitle());  
    $log->setClass('Display');  
    $log->save();
  }

  public function postUpdate($values)
  {
    $log = new Log();
    $log->setAction('Update');
    if(sfContext::hasInstance())
      $log->setUserId(sfContext::getInstance()->getUser()->getGuardUser()->getId());
    $log->setSiteId($this->Block->Section->Site->getId());
    $log->setAsset($this->getId());
    $log->setAssetTitle($this->getTitle());  
    $log->setClass('Display');  
    $log->save();
  }

  public function postInsert($values)
  {
    $log = new Log();
    $log->setAction('Insert');
    if(sfContext::hasInstance())
      $log->setUserId(sfContext::getInstance()->getUser()->getGuardUser()->getId());
    $log->setSiteId($this->Block->Section->Site->getId());
    $log->setAsset($this->getId());
    $log->setAssetTitle($this->getTitle());  
    $log->setClass('Display');  
    $log->save();
  }

  public function retriveLabel(){
    if($this->getLabel() != "")
      return $this->getLabel();
    elseif($this->Asset->Category->getTitle() != "")
      return $this->Asset->Category->getTitle();    
  }

  public function retriveImageUrlByImageUsage($usage){
    if(!$usage)
      $usage = "default";
    if($this->getImage() != ""){
      return "/uploads/displays/".$this->getImage();
    }
    elseif($this->Asset->AssetType->getSlug() == "image"){
      return "/uploads/assets/image/".$usage."/".$this->Asset->AssetImage->getFile().".jpg";
    }
    elseif($this->Asset->AssetType->getSlug() == "video"){
      return "http://img.youtube.com/vi/".$this->Asset->AssetVideo->getYoutubeId()."/0.jpg";
    }
    elseif($this->Asset->getId() > 0){
      $imgs = $this->Asset->retriveRelatedAssetsByAssetTypeId(2);
      if(count($imgs) > 0)
        return "/uploads/assets/image/".$usage."/".$imgs[0]->AssetImage->getFile().".jpg";
    }
  }

  public function retriveUrl(){
    if($this->Asset->getId() > 0)
      return "/asset/".$this->Asset->getId();
    elseif($this->url != "")
      return $this->url;
    else
      return "javascript:;";
  }

}
