<?php

/**
 * Program
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Program extends BaseProgram
{
  
  public function retriveUrl(){
    if($this->Site->getId() > 0){
      if($this->Site->getUrl() != "")
        return $this->Site->getUrl();
      else
        return "/".$this->Site->getSlug();
    }
    elseif($this->getSlug() != "")
      return "/".$this->getSlug();
    else
      return "javascript:;";
  }

  public function retriveLiveImage(){
    if($this->getImageLive() != "")
      return "/uploads/programs/".$this->getImageLive();
    elseif($this->Channels[0]->getImageThumb() != "")
      return "/uploads/programs/".$this->Channels[0]->getImageThumb();
  }

}
