<?php

/**
 * Section
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Section extends BaseSection
{
	
  public function __toString2()
  {
    return (string) $this->getTitle();
    /*
    if($this->Site->getTitle())
      return (string) $this->Site->getTitle()." > ".$this->getTitle();
    else
      return (string) $this->getTitle();
    */
  }

  public function __toString()
  {
    $return = "";
    if($this->Site->getTitle())
      $return .= $this->Site->getTitle()." > ";
    if($this->Parent->Parent->getTitle())
      $return .= $this->Parent->Parent->getTitle()." > ";
    if($this->Parent->getTitle())
      $return .= $this->Parent->getTitle()." > ";
    $return .= $this->getTitle();
    return $return;
  }

  public function postDelete($values)
  {
    $log = new Log();
    $log->setAction('Delete');
    if(sfContext::hasInstance())
      $log->setUserId(sfContext::getInstance()->getUser()->getGuardUser()->getId());
    $log->setSiteId($this->getSiteId());
    $log->setAsset($this->getId());
    $log->setAssetTitle($this->getTitle());  
    $log->setClass('Section');  
    $log->save();
  }

  public function postUpdate($values)
  {
    $log = new Log();
    $log->setAction('Update');
    if(sfContext::hasInstance())
      $log->setUserId(sfContext::getInstance()->getUser()->getGuardUser()->getId());
    $log->setSiteId($this->getSiteId());
    $log->setAsset($this->getId());
    $log->setAssetTitle($this->getTitle());  
    $log->setClass('Section');  
    $log->save();
  }

  public function postInsert($values)
  {
    $log = new Log();
    $log->setAction('Insert');
    if(sfContext::hasInstance())
      $log->setUserId(sfContext::getInstance()->getUser()->getGuardUser()->getId());
    $log->setSiteId($this->getSiteId());
    $log->setAsset($this->getId());
    $log->setAssetTitle($this->getTitle());  
    $log->setClass('Section');  
    $log->save();
  }

  public function retriveUrl()
  {
    return (string) url_for('homepage').$this->Site->getSlug()."/".$this->getSlug();
  }


}
