<?php

/**
 * SonyCategoryAssetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SonyCategoryAssetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SonyCategoryAssetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SonyCategoryAsset');
    }
}