<?php

/**
 * SonyCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SonyCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SonyCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SonyCategory');
    }
}