<?php

/**
 * SonyAssetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SonyAssetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SonyAssetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SonyAsset');
    }
}