<?php

/**
 * TrebuchetCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrebuchetCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrebuchetCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrebuchetCategory');
    }
}