<?php

/**
 * TrebuchetAssetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrebuchetAssetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrebuchetAssetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrebuchetAsset');
    }
}