<?php

/**
 * TrebuchetCategoryAssetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrebuchetCategoryAssetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrebuchetCategoryAssetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrebuchetCategoryAsset');
    }
}