<?php

/**
 * VideoDropboxTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VideoDropboxTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object VideoDropboxTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('VideoDropbox');
	}


	static public function applyVideoFilter($query, $value)
	{

		$ids = Doctrine_Query::create()
		->select('av.id')
		->from('AssetVideo av, Asset a')
		->where('av.asset_id = a.id')
		->andWhere('a.asset_type_id = ? OR a.asset_type_id = ?', array(6, 7))
		->andWhere('a.title LIKE ?', '%'.$value.'%')
		->orderBy('a.title')
		->execute();

		//var_dump($ids);
		//echo ">>>".$value["text"];

		$arr = Array();
		foreach($ids as $i){
			$arr[] = $i->id;
			//echo "<br />".$i->Asset->title;
		}
		//die(count($arr));
		//echo "<pre>";
		//var_dump($ids);
		//echo "</pre>";

		//die('>>>'.count($ids));

		$rootAlias = $query->getRootAlias();
		$query->whereIn($rootAlias.'.asset_video_id', $arr);
		return $query;
	}

}