generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SonyCategoryAsset
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sony_category_asset
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list: 
        max_per_page: 500
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
