generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SonyAsset
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sony_category_assets_add
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:            ""
        display:          [title, created_at]
        actions:          {}
        object_actions:   {}
        batch_actions:
          save:           ~
      filter:
        display:          [title, description]
      form:    ~
      edit:    ~
      new:     ~
