default:
  stylesheets:    [core.css, /js/jquery-ui-1.8.7/css/ui-lightness/jquery-ui-1.8.7.custom.css, /js/fancybox/fancybox/jquery.fancybox-1.3.4.css]
  javascripts:    [jquery-ui-1.8.7/jquery-1.4.4.min.js, jquery-ui-1.8.7/jquery-ui-1.8.7.custom.min.js, ckeditor/ckeditor.js, /sfFormExtraPlugin/js/double_list.js, fancybox/fancybox/jquery.fancybox-1.3.4.pack.js]

  newSuccess:
    stylesheets:    [core.css]
    javascripts:    [jquery-ui-1.8.7/jquery-1.4.4.min.js]
    has_layout:     true
    layout:         layout_min