<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('log', 'status', 'string', '255', array(
             ));
        $this->addColumn('section', 'is_homepage', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->changeColumn('asset_video', 'file', 'string', '255', array(
             ));
        $this->changeColumn('asset_video', 'original_file', 'string', '255', array(
             ));
        $this->changeColumn('asset_video', 'extension', 'string', '255', array(
             ));
        $this->changeColumn('asset_video', 'original_file_size', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('log', 'status');
        $this->removeColumn('section', 'is_homepage');
    }
}