<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('section', 'is_homepage');
    }

    public function down()
    {
        $this->addColumn('section', 'is_homepage', 'boolean', '25', array(
             'default' => '0',
             ));
    }
}