<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('view', 'url', 'string', '255', array(
             ));
        $this->addColumn('view', 'template', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('view', 'url');
        $this->removeColumn('view', 'template');
    }
}