<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('view', 'view_asset_id_asset_id');
        $this->dropForeignKey('view', 'view_section_id_section_id');
    }

    public function down()
    {
        $this->createForeignKey('view', 'view_asset_id_asset_id', array(
             'name' => 'view_asset_id_asset_id',
             'local' => 'asset_id',
             'foreign' => 'id',
             'foreignTable' => 'asset',
             ));
        $this->createForeignKey('view', 'view_section_id_section_id', array(
             'name' => 'view_section_id_section_id',
             'local' => 'section_id',
             'foreign' => 'id',
             'foreignTable' => 'section',
             ));
    }
}