<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('view', 'url');
        $this->removeColumn('view', 'template');
        $this->removeColumn('view', 'asset_id');
        $this->removeColumn('view', 'section_id');
        $this->addColumn('view', 'asset', 'integer', '8', array(
             ));
        $this->addColumn('view', 'section', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->addColumn('view', 'url', 'string', '255', array(
             ));
        $this->addColumn('view', 'template', 'string', '255', array(
             ));
        $this->addColumn('view', 'asset_id', 'integer', '8', array(
             ));
        $this->addColumn('view', 'section_id', 'integer', '8', array(
             ));
        $this->removeColumn('view', 'asset');
        $this->removeColumn('view', 'section');
    }
}