<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('section', 'keywords', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('section', 'keywords');
    }
}