<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('asset_video', 'start_from', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('asset_video', 'start_from');
    }
}