<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('section', 'contact_email', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('section', 'contact_email');
    }
}