<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('display', 'video_offset', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('display', 'video_offset');
    }
}