<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('task', 'task_parent_id_message_id', array(
             'name' => 'task_parent_id_message_id',
             'local' => 'parent_id',
             'foreign' => 'id',
             'foreignTable' => 'message',
             ));
        $this->createForeignKey('task', 'task_site_id_site_id', array(
             'name' => 'task_site_id_site_id',
             'local' => 'site_id',
             'foreign' => 'id',
             'foreignTable' => 'site',
             ));
        $this->addIndex('task', 'task_parent_id', array(
             'fields' => 
             array(
              0 => 'parent_id',
             ),
             ));
        $this->addIndex('task', 'task_site_id', array(
             'fields' => 
             array(
              0 => 'site_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('task', 'task_parent_id_message_id');
        $this->dropForeignKey('task', 'task_site_id_site_id');
        $this->removeIndex('task', 'task_parent_id', array(
             'fields' => 
             array(
              0 => 'parent_id',
             ),
             ));
        $this->removeIndex('task', 'task_site_id', array(
             'fields' => 
             array(
              0 => 'site_id',
             ),
             ));
    }
}