<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('video_dropbox', 'asset_video_gallery_id', 'integer', '8', array(
             ));
        $this->changeColumn('video_dropbox', 'asset_video_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('video_dropbox', 'asset_video_gallery_id');
    }
}