<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version17 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('asset_video_gallery', 'youtube_id', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('asset_video_gallery', 'youtube_id');
    }
}