<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('asset_episode', 'date_record', 'date', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('asset_episode', 'date_record');
    }
}