<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version28 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('asset_question', 'spreadsheet_id', 'string', '255', array(
             ));
        $this->addColumn('asset_question', 'worksheet_id', 'string', '255', array(
             ));
        $this->addColumn('tweet_monitor', 'title', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->changeColumn('asset_answer', 'asset_id', 'integer', '8', array(
             ));
        $this->changeColumn('asset_answer', 'asset_question_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('asset_question', 'spreadsheet_id');
        $this->removeColumn('asset_question', 'worksheet_id');
        $this->removeColumn('tweet_monitor', 'title');
    }
}