<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version29 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('video_dropbox', 'youtube_id', 'string', '255', array(
             ));
    }

    public function down()
    {

    }
}