<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version30 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('program', 'tv_rating', 'string', '255', array(
             ));
        $this->addColumn('program', 'tv_category', 'string', '255', array(
             ));
        $this->addColumn('schedule', 'tv_rating', 'string', '255', array(
             ));
        $this->addColumn('schedule', 'tv_category', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('program', 'tv_rating');
        $this->removeColumn('program', 'tv_category');
        $this->removeColumn('schedule', 'tv_rating');
        $this->removeColumn('schedule', 'tv_category');
    }
}