<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version33 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('schedule', 'is_geoblocked', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->changeColumn('asset', 'description', 'text', '610', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('schedule', 'is_geoblocked');
    }
}