<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version36 extends Doctrine_Migration_Base
{
    public function up()
    {
	/*
        $this->removeColumn('trebuchet_asset', 'category_id');
        $this->removeColumn('trebuchet_category', 'category_id');
        $this->removeColumn('trebuchet_category_asset', 'category_id');
        $this->removeColumn('trebuchet_category_asset', 'asset_id');
        $this->addColumn('trebuchet_category', 'trebuchet_category_id', 'integer', '8', array(
             ));
        $this->addColumn('trebuchet_category_asset', 'trebuchet_category_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('trebuchet_category_asset', 'trebuchet_asset_id', 'integer', '8', array(
             'notnull' => '1',
             ));
	*/
    }

    public function down()
    {
        $this->addColumn('trebuchet_asset', 'category_id', 'integer', '8', array(
             ));
        $this->addColumn('trebuchet_category', 'category_id', 'integer', '8', array(
             ));
        $this->addColumn('trebuchet_category_asset', 'category_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('trebuchet_category_asset', 'asset_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->removeColumn('trebuchet_category', 'trebuchet_category_id');
        $this->removeColumn('trebuchet_category_asset', 'trebuchet_category_id');
        $this->removeColumn('trebuchet_category_asset', 'trebuchet_asset_id');
    }
}
