<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version42 extends Doctrine_Migration_Base
{
    public function up()
    {

        //$this->removeColumn('trebuchet_asset', 'category_id');
        //$this->removeColumn('trebuchet_category', 'category_id');

        //$this->addColumn('trebuchet_category', 'trebuchet_category_id', 'integer', '8', array());
        //$this->addColumn('trebuchet_asset', 'trebuchet_asset_id', 'integer', '8', array());

	/*

        $this->dropForeignKey('trebuchet_asset', 'trebuchet_asset_category_id_trebuchet_category_id');
        $this->dropForeignKey('trebuchet_asset', 'trebuchet_asset_category_id_category_id');
        $this->dropForeignKey('trebuchet_category', 'trebuchet_category_category_id_trebuchet_category_id');
        $this->dropForeignKey('trebuchet_category', 'trebuchet_category_category_id_category_id');
        $this->createForeignKey('trebuchet_category', 'trebuchet_category_trebuchet_category_id_trebuchet_category_id', array(
             'name' => 'trebuchet_category_trebuchet_category_id_trebuchet_category_id',
             'local' => 'trebuchet_category_id',
             'foreign' => 'id',
             'foreignTable' => 'trebuchet_category',
             ));
        $this->addIndex('trebuchet_category', 'trebuchet_category_trebuchet_category_id', array(
             'fields' => 
             array(
              0 => 'trebuchet_category_id',
             ),
             ));
	*/
    }

    public function down()
    {
        $this->createForeignKey('trebuchet_asset', 'trebuchet_asset_category_id_trebuchet_category_id', array(
             'name' => 'trebuchet_asset_category_id_trebuchet_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'trebuchet_category',
             ));
        $this->createForeignKey('trebuchet_asset', 'trebuchet_asset_category_id_category_id', array(
             'name' => 'trebuchet_asset_category_id_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'category',
             ));
        $this->createForeignKey('trebuchet_category', 'trebuchet_category_category_id_trebuchet_category_id', array(
             'name' => 'trebuchet_category_category_id_trebuchet_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'trebuchet_category',
             ));
        $this->createForeignKey('trebuchet_category', 'trebuchet_category_category_id_category_id', array(
             'name' => 'trebuchet_category_category_id_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'category',
             ));
        $this->dropForeignKey('trebuchet_category', 'trebuchet_category_trebuchet_category_id_trebuchet_category_id');
        $this->removeIndex('trebuchet_category', 'trebuchet_category_trebuchet_category_id', array(
             'fields' => 
             array(
              0 => 'trebuchet_category_id',
             ),
             ));
    }
}
