generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Asset
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          asset_display_assets
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:            ""
        display:          [id, AssetType, Site, thumbnail, title]
        actions:          {}
        object_actions:   {}
        batch_actions:
          save:           ~
        max_per_page: 90
      filter:
        display:          [title, asset_type_id, site_id]
      form:    ~
      edit:    ~
      new:     ~
